Repository kminsmin/BlueBlackBlocks, pull requests merged in 2023-10, with the labels that each got.

#8 Feature/#7 CustomGenericSingleton
  Client/Assets/Scripts.meta
  Client/Assets/Scripts/Managers.meta
  Client/Assets/Scripts/Utils.meta
  Client/Assets/Scripts/Utils/CustomSingleton.cs
  Client/Assets/Scripts/Utils/CustomSingleton.cs.meta
Labels: Feature

#12 Feature/#5 Server 초기 코드
  Client/Assets/Scripts/Packet.meta
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Packet/ClientPacketManager.cs.meta
  Client/Assets/Scripts/Packet/GenPackets.cs
  Client/Assets/Scripts/Packet/GenPackets.cs.meta
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs.meta
  Client/Assets/Scripts/Packet/PacketQueue.cs
  Client/Assets/Scripts/Packet/PacketQueue.cs.meta
  Client/Assets/Scripts/Packet/ServerSession.cs
  Client/Assets/Scripts/Packet/ServerSession.cs.meta
  Client/Assets/Scripts/ServerCore.meta
  Client/Assets/Scripts/ServerCore/Connector.cs
  Client/Assets/Scripts/ServerCore/Connector.cs.meta
  Client/Assets/Scripts/ServerCore/RecvBuffer.cs
  Client/Assets/Scripts/ServerCore/RecvBuffer.cs.meta
  Client/Assets/Scripts/ServerCore/SendBuffer.cs
  Client/Assets/Scripts/ServerCore/SendBuffer.cs.meta
  Client/Assets/Scripts/ServerCore/Session.cs
  Client/Assets/Scripts/ServerCore/Session.cs.meta
  Common/Packet/ClientPacketManager.cs
  Common/Packet/GenPackets.bat
  Common/Packet/GenPackets.cs
  Common/Packet/ServerPacketManager.cs
  Server/.gitignore
  Server/DummyClient/Packet/ClientPacketManager.cs
  Server/DummyClient/Packet/GenPackets.cs
  Server/DummyClient/Packet/PacketHandler.cs
  Server/DummyClient/Program.cs
  Server/DummyClient/ServerSession.cs
  Server/DummyClient/SessionManager.cs
  Server/PacketGenerator/PDL.xml
  Server/PacketGenerator/PacketFormat.cs
  Server/PacketGenerator/Program.cs
  Server/Server/DB/AppDbContext.cs
  Server/Server/DB/DataModel.cs
  Server/Server/GameRoom.cs
  Server/Server/JobTimer.cs
  Server/Server/Packet/GenPackets.cs
  Server/Server/Packet/PacketHandler.cs
  Server/Server/Packet/ServerPacketManager.cs
  Server/Server/Program.cs
  Server/Server/Session/ClientSession.cs
  Server/Server/Session/SessionManager.cs
  Server/ServerCore/Connector.cs
  Server/ServerCore/JobQueue.cs
  Server/ServerCore/Listener.cs
  Server/ServerCore/PriorityQueue.cs
  Server/ServerCore/RecvBuffer.cs
  Server/ServerCore/SendBuffer.cs
  Server/ServerCore/Session.cs
Labels: Feature

#15 UI/#14 CharacterAnimator
  Client/Assets/Animations.meta
  Client/Assets/Animations/Character.meta
  Client/Assets/Animations/Character/Virtual Guy.meta
  Client/Assets/Animations/Character/Virtual Guy/Animator Controller.controller
  Client/Assets/Animations/Character/Virtual Guy/Animator Controller.controller.meta
  Client/Assets/Animations/Character/Virtual Guy/Appearing.anim
  Client/Assets/Animations/Character/Virtual Guy/Appearing.anim.meta
  Client/Assets/Animations/Character/Virtual Guy/Desappearing.anim
  Client/Assets/Animations/Character/Virtual Guy/Desappearing.anim.meta
  Client/Assets/Animations/Character/Virtual Guy/Hit.anim
  Client/Assets/Animations/Character/Virtual Guy/Hit.anim.meta
  Client/Assets/Animations/Character/Virtual Guy/Idle.anim
  Client/Assets/Animations/Character/Virtual Guy/Idle.anim.meta
  Client/Assets/Animations/Character/Virtual Guy/Jump.anim
  Client/Assets/Animations/Character/Virtual Guy/Jump.anim.meta
  Client/Assets/Animations/Character/Virtual Guy/Run.anim
  Client/Assets/Animations/Character/Virtual Guy/Run.anim.meta
  Client/Assets/Animations/Character/Virtual Guy/Wall Jump.anim
  Client/Assets/Animations/Character/Virtual Guy/Wall Jump.anim.meta
  Client/Assets/External/Pixel Adventure 1/Assets/Main Characters/Virtual Guy/Double Jump (32x32).png.meta
  Client/Assets/External/Pixel Adventure 1/Assets/Main Characters/Virtual Guy/Fall (32x32).png.meta
  Client/Assets/External/Pixel Adventure 1/Assets/Main Characters/Virtual Guy/Hit (32x32).png.meta
  Client/Assets/External/Pixel Adventure 1/Assets/Main Characters/Virtual Guy/Idle (32x32).png.meta
  Client/Assets/External/Pixel Adventure 1/Assets/Main Characters/Virtual Guy/Jump (32x32).png.meta
  Client/Assets/External/Pixel Adventure 1/Assets/Main Characters/Virtual Guy/Run (32x32).png.meta
  Client/Assets/External/Pixel Adventure 1/Assets/Main Characters/Virtual Guy/Wall Jump (32x32).png.meta
  Client/Assets/Scenes/StartScene.unity
  Client/Assets/Scenes/StartScene.unity.meta
  Client/Assets/Scripts/AnimationTest.cs
  Client/Assets/Scripts/AnimationTest.cs.meta
Labels: UI

#20 Fix/Cutscene
  Client/Assets/Resources/Data/IntroCutDialogue.asset
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Timeline/IntroCut.playable
Labels: Fix

#29 Feature/#27 WebManager
  Client/Assets/NuGet.config
  Client/Assets/NuGet.config.meta
  Client/Assets/Packages.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/.signature.p7s
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/LICENSE.md
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/LICENSE.md.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/Newtonsoft.Json.nuspec
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/Newtonsoft.Json.nuspec.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/README.md
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/README.md.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/lib.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/lib/netstandard2.0.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/lib/netstandard2.0/Newtonsoft.Json.dll
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/lib/netstandard2.0/Newtonsoft.Json.dll.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/lib/netstandard2.0/Newtonsoft.Json.xml
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/lib/netstandard2.0/Newtonsoft.Json.xml.meta
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/packageIcon.png
  Client/Assets/Packages/Newtonsoft.Json.13.0.3/packageIcon.png.meta
  Client/Assets/Scripts/Managers/WebManager.cs
  Client/Assets/Scripts/Managers/WebManager.cs.meta
  Client/Assets/Scripts/Web.meta
  Client/Assets/Scripts/Web/WebPacket.cs
  Client/Assets/Scripts/Web/WebPacket.cs.meta
  Client/Assets/packages.config
  Client/Assets/packages.config.meta
  Client/Packages/manifest.json
  Client/Packages/packages-lock.json
  Client/app.config
Labels: Feature

#39 Docs/Readme 초안
  README.md
Labels: Docs

#45 CutScene Skip Button
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Scripts/Entities/CheckPoint.cs
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Feature

#46 Feature/#44 웹패킷 정의 및 url 수정
  Client/Assets/Scripts/Managers/WebManager.cs
  Client/Assets/Scripts/Web/WebPacket.cs
  Server/AccountServer/Controllers/AccountController.cs
  Server/AccountServer/DB/WebPacket.cs
  Server/AccountServer/Utils/Define.cs
Labels: Feature

#48 Refactor/#47 웹앱 설정 수정 및 Readme 파일 수정
  README.md
  Server/AccountServer/Program.cs
Labels: Refactor

#51 UI/#50 Login&SceneLoad
  Client/Assets/Scripts/Managers/UIManager.cs
  Client/Assets/Scripts/Managers/WebManager.cs
  Client/Assets/Scripts/UI/UILogin.cs
Labels: UI

#53 cut scene seperated, gamescene sync
  Client/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Client/Assets/Resources/Enemies.meta
  Client/Assets/Resources/Enemies/Rockhead.prefab
  Client/Assets/Resources/Enemies/Rockhead.prefab.meta
  Client/Assets/Resources/Platforms/FallingPlatform.prefab
  Client/Assets/Resources/Player.prefab
  Client/Assets/Resources/Player.prefab.meta
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Scenes/IntroScene.unity
  Client/Assets/Scenes/IntroScene.unity.meta
  Client/Assets/Scripts/Entities/CheckPoint.cs
  Client/Assets/Scripts/Entities/FallingPlatform.cs
  Client/Assets/Scripts/Entities/Rockhead.cs
  Client/Assets/Scripts/Entities/SkipButton.cs
  Client/Assets/Scripts/Entities/SkipButton.cs.meta
  Client/Assets/Scripts/Managers/StageManager.cs
  Client/ProjectSettings/EditorBuildSettings.asset
Labels: Feature

#55 Fix/#49 로그인 시 비밀번호 검증
  Server/AccountServer/Controllers/AccountController.cs
Labels: Fix

#57 Feature/#23 Switch Player to Photon PUN2
  Client/Assets/Prefabs/Player.prefab
  Client/Assets/Scripts/Player/Animator/PlayerAnimator.cs
  Client/Assets/Scripts/Player/CameraSetup.cs
  Client/Assets/Scripts/Player/CameraSetup.cs.meta
  Client/Assets/Scripts/Player/Controller/PlayerController.cs
Labels: Feature

#60 GameSceneFix
  Client/Assets/Prefabs/Player.prefab
  Client/Assets/Prefabs/Player.prefab.meta
  Client/Assets/Resources/Player.prefab
  Client/Assets/Resources/Player.prefab.meta
Labels: Fix

#62 GameScene fix
  Client/Assets/Resources/Palettes/TrapPalette.prefab
  Client/Assets/Resources/Player.prefab
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Fix

#63 Player Spawn Fix
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Fix

#64 Fixing GameScene
  Client/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Client/Assets/Resources/Palettes/TrapPalette.prefab
  Client/Assets/Resources/Player.prefab
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Fix

#65 Player Spawn Fix
  Client/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Client/Assets/Resources/Enemies/Rockhead.prefab
  Client/Assets/Resources/Palettes/TrapPalette.prefab
  Client/Assets/Resources/Platforms/FallingPlatform.prefab
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Scenes/IntroScene.unity
  Client/Assets/Scripts/Entities/SkipButton.cs
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Fix

#69 Feature/#52
  Client/Assets/Resources/Palettes/TrapPalette.prefab
  Client/Assets/Resources/Player_Black.prefab
  Client/Assets/Scripts/Entities/FallingPlatform.cs
  Client/Assets/Scripts/Managers/StageManager.cs
  Client/Assets/Scripts/Player/Controller/PlayerController.cs
Labels: Fix

#70 Fix jump sync
  Client/Assets/Resources/Enemies/Rockhead.prefab
  Client/Assets/Resources/Palettes/TrapPalette.prefab
  Client/Assets/Resources/Platforms/FallingPlatform.prefab
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Scripts/Entities/CheckJump.cs
  Client/Assets/Scripts/Entities/CheckJump.cs.meta
  Client/Assets/Scripts/Entities/FallingPlatform.cs
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Fix

#72 Feature/#52
  Client/Assets/Resources/Platforms/FallingPlatform.prefab
  Client/Assets/Scenes/GameScene.unity
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Fix

#74 Fix Player Prefab
  Client/Assets/Resources/Player.prefab
  Client/Assets/Resources/Player_Black.prefab
  Client/Assets/Scripts/Managers/StageManager.cs
Labels: Fix

#75 Docs/Readme 파일 최종본
  README.md
Labels: Docs
